### ISSUE TITLE
Поддержка  MySQL 5.7 и PHP 7

### ISSUE THREAD

**Issue by Redleks** [OkayCMS/Okay_Lite#1]
В MySQL версии 5.7+ по умолчанию включен strict mode, который запрещает ввод неправильных данных. Соответственно при развертывании базы выкидывается ошибка Invalid default value for ... везде где стоят неправильные данные. Например timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' в таблице s_blog. 

Так же в PHP 7 функция mysql_connect is deprecated что так же не дает нормально установить базу.

Думаю стоит это поправить, так как многие хостеры уже давно перехали на стэк PHP 7 + MySQL 5.7

**Comment by OkayCMS** [comment]
Да, это будет исправлено в версии 2.0 которая ожидается через месяц-полтора.
